---
- name: Create target directory
  file: path=/tmp/RPMS state=directory mode=0755
  ignore_errors: True

- name: Copy the nginx_nginx_packages
  copy: src=RPM/{{ item }} dest=/tmp/RPMS
  with_items: nginx_packages
    
- name: Copy the ssl dir
  copy: src=files/ssl dest=/etc/nginx/ssl

- name: Install the nginx_nginx_packages
  yum: name=/tmp/RPMS/{{ item }} state=installed
  with_items: nginx_packages

- name: nginx conf file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Creates vhosts directory
  file: 
    path: /etc/nginx/vhosts 
    state: directory
    owner: root
    group: analytics        
